chat-prefix: "&#FE6847[&#FBB13CLoneWeek TreasureHunt&#FE6847] "
scoreboard-id: "punteggiotreasurehunt"

min-distance-from-center: 1000
max-distance-from-center: 3500

# If chest is broken the closest player gets these points
points-to-opener: 20
# If chest is open or broken and the player is close enough they will get these points
points-to-close: 5
# Max distance of entities to be assigned points.
close-range: 100

#the name of the npc needs to contain the following substring
npc-name: "Cartograf"

#strings
#{player} - subject
#{points}
win-broadcast-message: "&#FE6847{player} &#57B8FFha trovato un tesore e ha vinto &#FE6847{points}&#57B8FF punti!"
close-win-private-message: "&#57B8FFCongratulazioni per aver contribuito a trovare il tesoro, hai vinto &#FE6847{points}&#57B8FF punti!"

success-generate-map: "&#57B8FFHai generato una mappa che punta al tesoro più vicino"
error-not-enough-space: "&#57B8FFNon hai abbastanza spazio nell'inventario"
error-no-treasure-world: "&#57B8FFIn questo momento non ci sono tesori in questo mondo"
error-no-treasure: "&#57B8FFIn questo momento non ci sono tesori nel server"
error-no-map-in-hand: "&#57B8FFDevi avere in mano una mappa vuota per poter usare questo comando"

prizes-in-treasure:
  - treasure:
    - material: DIAMOND_SWORD
      name: "&6Spada del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 1
    - material: OXEYE_DAISY
      amount: 1
    - material: RED_CANDLE
      amount: 10
  - treasure:
    - material: NETHER_WART
      amount: 1
    - material: BEACON
      name: "&6Faro del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 1
    - material: WHITE_CANDLE
      amount: 10
  - treasure:
    - material: SUGAR_CANE
      amount: 6
    - material: DIAMOND_AXE
      name: "&6Ascia del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 3
    - material: GRAY_CANDLE
      amount: 10
  - treasure:
    - material: RED_MUSHROOM
      amount: 1
    - material: ARROW
      name: "&6Frecce del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 32
    - material: BLUE_CANDLE
      amount: 10
  - treasure:
    - material: HONEYCOMB
      amount: 1
    - material: SPECTRAL_ARROW
      name: "&6Frecce spettrali del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 10
    - material: ORANGE_CANDLE
      amount: 10
  - treasure:
    - material: PRISMARINE_SHARD
      amount: 1
    - material: BOW
      name: "&6Arco del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 1
    - material: YELLOW_CANDLE
      amount: 10
  - treasure:
    - material: STICK
      amount: 1
    - material: EXPERIENCE_BOTTLE
      name: "&6Esperienza del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 10
    - material: GREEN_CANDLE
      amount: 10
  - treasure:
    - material: CHAIN
      amount: 1
    - material: GHAST_TEAR
      name: "&6Lacrime del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 1
    - material: LIME_CANDLE
      amount: 10
  - treasure:
    - material: SMALL_DRIPLEAF
      amount: 1
    - material: PAPER
      name: "&6Carta del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      amount: 1
    - material: PINK_CANDLE
      amount: 10
  - treasure:
    - material: AZURE_BLUET
      amount: 1
    - material: ENCHANTED_BOOK
      name: "&6Magia del Tesoriero"
      lore:
        - "&7LoneWeek - Treasure Hunt"
      enchantments:
        LUCK_OF_THE_SEA: 1
    - material: PURPLE_CANDLE
      amount: 10


debug: true